[context]
name = "nekit.dev"
version = "0.1.0"
url = "https://github.com/nekitdev/nekit.dev"

[formats]
title = "[{{version}}]({{url}}/tree/v{{version}}) ({{date}})"
fragment = "{{content}} ([#{{id}}]({{url}}/pull/{{id}}))"
