[package]
name = "nekit-serve"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Serving static files."
readme = "README.md"
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies.anyhow]
workspace = true
features = ["std"]

[dependencies.axum]
workspace = true
features = ["default"]

[dependencies.clap]
workspace = true
features = ["default", "derive", "env"]

[dependencies.thiserror]
workspace = true
features = ["std"]

[dependencies.tokio]
workspace = true
features = ["full"]

[dependencies.tower-http]
workspace = true
features = ["fs"]
