[package]
name = "nekit-dev"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Personal website."
readme = "README.md"
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies.dioxus]
workspace = true
features = ["default", "fullstack", "router"]

[dependencies.jiff]
workspace = true
features = ["default"]

[dependencies.pid1]
workspace = true
optional = true

[dependencies.refining]
workspace = true
features = ["default"]

[dependencies.reqwest]
workspace = true
features = ["default", "json"]

[dependencies.serde]
workspace = true
features = ["std", "derive"]

[features]
default = ["web"]
web = ["dioxus/web"]
server = ["dioxus/server", "pid1"]
